import json


'''
This docstring is here to show the categories that each braille key fit in to. Some alterations have been made. 
Example: "in" fits into several categories but I had to place it in one category to allow my software to work.

# lowercase = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
# punctuation = ["!", "\"", "#", "$", "%", "&", "'", "(", ")", "*", "+", ",", "-", ".", "/", ":", ";", "<", "=", ">", "?", "@", "[", "\\", "]", "^", "_", "{", "}", "°", " ", "\n"]
# digits = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
# alpha_wordsigns = ["but", "can", "do", "every", "from", "go", "have", "just", "knowledge", "like", "more", "not", "people", "quite", "rather", "so", "that", "us", "very", "will", "it", "you", "as"]
# initial_letter_contractions = ["day", "ever", "father", "here", "know", "lord", "mother", "name", "one", "part", "question", "right", "some", "time", "under", "work", "young", "there", "character", "through", "where", "ought", "upon", "word", "these", "those", "whose", "cannot", "had", "many", "spirit", "world", "their"]
# strong_groupsigns = ["ch", "sh", "th", "wh", "ou", "st", "gh", "ed", "er", "ow", "ar", "in"]
# strong_contraction = ["and", "for", "of", "the", "with"]
# strong_wordsigns = ["child","shall","this","which","out","still"]
# lower_wordsigns = ["be","enough","were","his","was"]
# lower_groupsigns = ["ea", "bb", "cc", "ff", "gg", "be", "con", "dis", "en"]
# shortform_words = ["about", "above", "according", "across", "after", "afternoon", "afterward", "again", "against", "almost", "already", "also", "although", "altogether", "always", "because", "before", "behind", "below", "beneath", "beside", "between", "beyond", "blind", "braille", "children", "conceive", "conceiving", "could", "deceive", "deceiving", "declare", "declaring", "either", "first", "friend", "good", "great", "herself", "him", "himself", "immediate", "its", "itself", "letter", "little", "much", "must", "myself", "necessary", "neither", "oneself", "ourselves", "paid", "perceive", "perceiving", "perhaps", "quick", "receive", "receiving", "rejoice", "rejoicing", "said", "should", "such", "themselves", "thyself", "today", "together", "tomorrow", "tonight", "would", "your", "yourself", "yourselves"]
# final_letter_groupsigns = ["ound", "ance", "sion", "less", "ount", "ence", "ong", "ful", "tion", "ness", "ment", "ity"]
'''

braille = {
"a": {"type": "lowercase", "value": [(1,)]},
"b": {"type": "lowercase", "value": [(1,2)]},
"c": {"type": "lowercase", "value": [(1,4)]},
"d": {"type": "lowercase", "value": [(1,4,5)]},
"e": {"type": "lowercase", "value": [(1,5)]},
"f": {"type": "lowercase", "value": [(1,2,4)]},
"g": {"type": "lowercase", "value": [(1,2,4,5)]},
"h": {"type": "lowercase", "value": [(1,2,5)]},
"i": {"type": "lowercase", "value": [(2,4)]},
"j": {"type": "lowercase", "value": [(2,4,5)]},
"k": {"type": "lowercase", "value": [(1,3)]},
"l": {"type": "lowercase", "value": [(1,2,3)]},
"m": {"type": "lowercase", "value": [(1,3,4)]},
"n": {"type": "lowercase", "value": [(1,3,4,5)]},
"o": {"type": "lowercase", "value": [(1,3,5)]},
"p": {"type": "lowercase", "value": [(1,2,3,4)]},
"q": {"type": "lowercase", "value": [(1,2,3,4,5)]},
"r": {"type": "lowercase", "value": [(1,2,3,5)]},
"s": {"type": "lowercase", "value": [(2,3,4)]},
"t": {"type": "lowercase", "value": [(2,3,4,5)]},
"u": {"type": "lowercase", "value": [(1,3,6)]},
"v": {"type": "lowercase", "value": [(1,2,3,6)]},
"w": {"type": "lowercase", "value": [(2,4,5,6)]},
"x": {"type": "lowercase", "value": [(1,3,4,6)]},
"y": {"type": "lowercase", "value": [(1,3,4,5,6)]},
"z": {"type": "lowercase", "value": [(1,3,5,6)]},
"1": {"type": "digits", "value": [(1,)]},
"2": {"type": "digits", "value": [(1,2)]},
"3": {"type": "digits", "value": [(1,4)]},
"4": {"type": "digits", "value": [(1,4,5)]},
"5": {"type": "digits", "value": [(1,5)]},
"6": {"type": "digits", "value": [(1,2,4)]},
"7": {"type": "digits", "value": [(1,2,4,5)]},
"8": {"type": "digits", "value": [(1,2,5)]},
"9": {"type": "digits", "value": [(2,4)]},
"0": {"type": "digits", "value": [(2,4,5)]},
"!":  {"type": "punctuation", "value": [(2,3,5)]},          
"\"": {"type": "punctuation", "value": [(5,), (2,3,5,6)]},  
"#":  {"type": "punctuation", "value": [(3,4,5,6)]},   
"$":  {"type": "punctuation", "value": [(4,),(2,3,4)]},        
"%":  {"type": "punctuation", "value": [(4,6),(3,5,6)]},            
"•":  {"type": "punctuation", "value": [(4,5,6),(2,5,6)]}, 
"&":  {"type": "punctuation", "value": [(1,2,3,4,6)]},  
"'":  {"type": "punctuation", "value": [(3,)]},    
"(":  {"type": "punctuation", "value": [(5,), (1,2,6)]},    
")":  {"type": "punctuation", "value": [(5,), (3,4,5)]},   
"*":  {"type": "punctuation", "value": [(5,),(3,5)]},  
"+":  {"type": "punctuation", "value": [(3,4,6)]}, 
",":  {"type": "punctuation", "value": [(2,)]},
"-":  {"type": "punctuation", "value": [(3,6)]}, 
".":  {"type": "punctuation", "value": [(2,5,6)]},
"/":  {"type": "punctuation", "value": [(3,4)]}, 
":":  {"type": "punctuation", "value": [(2,5)]},
";":  {"type": "punctuation", "value": [(2,3)]}, 
"<":  {"type": "punctuation", "value": [(4,),(1,2,6)]},
"=":  {"type": "punctuation", "value": [(5,),(2,3,5,6)]}, 
">":  {"type": "punctuation", "value": [(4,),(3,4,5)]}, 
"?":  {"type": "punctuation", "value": [(2,3,6)]}, 
"@":  {"type": "punctuation", "value": [(4,),(1,)]}, 
"[":  {"type": "punctuation", "value": [(5,), (1,2,6)]},
"\\": {"type": "punctuation", "value": [((4,5,6),(1,6))]},   
"]":  {"type": "punctuation", "value": [(5,), (3,4,5)]}, 
"^":  {"type": "punctuation", "value": [(4,5),(1,4,6)]}, 
"_":  {"type": "punctuation", "value": [(4,6),(3,6)]},  
"{":  {"type": "punctuation", "value": [(4,5,6),(1,2,6)]}, 
"}":  {"type": "punctuation", "value": [(4,5,6),(3,4,5)]}, 
"°":  {"type": "punctuation", "value": [(4,5),(2,4,5)]}, 
" ":  {"type": "punctuation", "value": [("space",)]},
"\n": {"type": "punctuation", "value": [("Newline",)]},
"ch": {"type": "strong_groupsigns", "value": [(1,6)]},
"sh": {"type": "strong_groupsigns", "value": [(1,4,6)]},
"th": {"type": "strong_groupsigns", "value": [(1,4,5,6)]},
"wh": {"type": "strong_groupsigns", "value": [(1,5,6)]},
"ou": {"type": "strong_groupsigns", "value": [(1,2,5,6)]},
"st": {"type": "strong_groupsigns", "value": [(3,4)]},
"gh": {"type": "strong_groupsigns", "value": [(1,2,6)]},
"ed": {"type": "strong_groupsigns", "value": [(1,2,4,6)]},
"er": {"type": "strong_groupsigns", "value": [(1,2,4,5,6)]},
"ow": {"type": "strong_groupsigns", "value": [(2,4,6)]},
"ar": {"type": "strong_groupsigns", "value": [(3,4,5)]},
"in": {"type": "strong_groupsigns", "value": [(3,5)]},
"and": {"type": "strong_contraction", "value": [(1,2,3,4,6)]},
"for": {"type": "strong_contraction", "value": [(1,2,3,4,5,6)]},
"of":  {"type": "strong_contraction", "value": [(1,2,3,5,6)]},
"the": {"type": "strong_contraction", "value": [(2,3,4,6)]},
"with": {"type": "strong_contraction", "value": [(2,3,4,5,6)]},
"day":       {"type": "initial_letter_contractions", "value": [(5,),(1,4,5)]},
"ever":      {"type": "initial_letter_contractions", "value": [(5,),(1,5)]},
"father":    {"type": "initial_letter_contractions", "value": [(5,),(1,2,4)]},
"here":      {"type": "initial_letter_contractions", "value": [(5,),(1,2,5)]},
"know":      {"type": "initial_letter_contractions", "value": [(5,),(1,3)]},
"lord":      {"type": "initial_letter_contractions", "value": [(5,),(1,2,3)]},
"mother":    {"type": "initial_letter_contractions", "value": [(5,),(1,3,4)]},
"name":      {"type": "initial_letter_contractions", "value": [(5,),(1,3,4,5)]},
"one":       {"type": "initial_letter_contractions", "value": [(5,),(1,3,5)]},
"part":      {"type": "initial_letter_contractions", "value": [(5,),(1,2,3,4)]},
"question":  {"type": "initial_letter_contractions", "value": [(5,),(1,2,3,4,5)]},
"right":     {"type": "initial_letter_contractions", "value": [(5,),(1,2,3,5)]},
"some":      {"type": "initial_letter_contractions", "value": [(5,),(2,3,4)]},
"time":      {"type": "initial_letter_contractions", "value": [(5,),(2,3,4,5)]},
"under":     {"type": "initial_letter_contractions", "value": [(5,),(1,3,6)]},
"work":      {"type": "initial_letter_contractions", "value": [(5,),(2,4,5,6)]},
"young":     {"type": "initial_letter_contractions", "value": [(5,),(1,3,4,5,6)]},
"there":     {"type": "initial_letter_contractions", "value": [(5,),(2,3,4,6)]},
"character": {"type": "initial_letter_contractions", "value": [(5,),(1,6)]}, 
"through":   {"type": "initial_letter_contractions", "value": [(5,),(1,4,5,6)]},
"where":     {"type": "initial_letter_contractions", "value": [(5,),(1,5,6)]},
"ought":     {"type": "initial_letter_contractions", "value": [(5,),(1,2,5,6)]},
"upon":      {"type": "initial_letter_contractions", "value": [(4,5),(1,3,6)]},
"word":      {"type": "initial_letter_contractions", "value": [(4,5),(2,4,5,6)]},
"these":     {"type": "initial_letter_contractions", "value": [(4,5),(2,3,4,6)]},
"those":     {"type": "initial_letter_contractions", "value": [(4,5),(1,4,5,6)]},
"whose":     {"type": "initial_letter_contractions", "value": [(4,5),(1,5,6)]},
"cannot":    {"type": "initial_letter_contractions", "value": [(4,5,6),(1,4)]},
"had":       {"type": "initial_letter_contractions", "value": [(4,5,6),(1,2,5)]},
"many":      {"type": "initial_letter_contractions", "value": [(4,5,6),(1,3,4)]},
"spirit":    {"type": "initial_letter_contractions", "value": [(4,5,6),(2,3,4)]},
"world":     {"type": "initial_letter_contractions", "value": [(4,5,6),(2,4,5,6)]},
"their":     {"type": "initial_letter_contractions", "value": [(4,5,6),(2,3,4,6)]},
"ea":  {"type": "lower_groupsigns", "value": [(2,)]},
"bb":  {"type": "lower_groupsigns", "value": [(2,3)]},
"cc":  {"type": "lower_groupsigns", "value": [(2,5)]},
"ff":  {"type": "lower_groupsigns", "value": [(2,3,5)]},
"gg":  {"type": "lower_groupsigns", "value": [(2,3,5,6)]},
"be":  {"type": "lower_groupsigns", "value": [(2,3)]},      
"con": {"type": "lower_groupsigns", "value": [(2,5)]},
"dis": {"type": "lower_groupsigns", "value": [(2,5,6)]},
"en":  {"type": "lower_groupsigns", "value": [(2,6)]},
"enough": {"type": "lower_wordsigns", "value": [(2,6)]},
"were":   {"type": "lower_wordsigns", "value": [(2,3,5,6)]},
"his":    {"type": "lower_wordsigns", "value": [(2,3,6)]},
"was":    {"type": "lower_wordsigns", "value": [(3,5,6)]},
"child": {"type": "strong_wordsigns", "value": [(1,6)]},
"shall": {"type": "strong_wordsigns", "value": [(1,4,6)]},
"this":  {"type": "strong_wordsigns", "value": [(1,4,5,6)]},
"which": {"type": "strong_wordsigns", "value": [(1,5,6)]},
"out":   {"type": "strong_wordsigns", "value": [(1,2,5,6)]},
"still": {"type": "strong_wordsigns", "value": [(3,4)]},
"about":       {"type": "shortform_words", "value": [(1,), (1,2)]}, 
"above":       {"type": "shortform_words", "value": [(1,), (1,2),(1,2,3,6)]}, 
"according":   {"type": "shortform_words", "value": [(1,),(1,4)]},  
"across":      {"type": "shortform_words", "value": [(1,),(1,4),(1,2,3,5)]},  
"after":       {"type": "shortform_words", "value": [(1,),(1,2,4)]}, 
"afternoon":   {"type": "shortform_words", "value": [(1,),(1,2,4),(1,3,4,5)]}, 
"afterward":   {"type": "shortform_words", "value": [(1,),(1,2,4),(2,4,5,6)]},
"again":       {"type": "shortform_words", "value": [(1,), (1,2,4,5)]}, 
"against":     {"type": "shortform_words", "value": [(1,), (1,2,4,5), (3,4)]},
"almost":      {"type": "shortform_words", "value": [(1,), (1,2,3), (1,3,4)]},
"already":     {"type": "shortform_words", "value": [(1,), (1,2,3), (1,2,3,5)]},
"also":        {"type": "shortform_words", "value": [(1,), (1,2,3)]},
"although":    {"type": "shortform_words", "value": [(1,), (1,2,3),(1,4,5,6)]},
"altogether":  {"type": "shortform_words", "value": [(1,),(1,2,3),(2,3,4,5)]},
"always":      {"type": "shortform_words", "value": [(1,), (1,2,3), (2,4,5,6)]},
"because":     {"type": "shortform_words", "value": [(2,3), (1,4)]}, 
"before":      {"type": "shortform_words", "value": [(2,3), (1,2,4)]}, 
"behind":      {"type": "shortform_words", "value": [(2,3), (1,2,5)]}, 
"below":       {"type": "shortform_words", "value": [(2,3), (1,2,3)]}, 
"beneath":     {"type": "shortform_words", "value": [(2,3), (1,3,4,5)]}, 
"beside":      {"type": "shortform_words", "value": [(2,3), (2,3,4)]},
"between":     {"type": "shortform_words", "value": [(2,3), (2,3,4,5)]}, 
"beyond":      {"type": "shortform_words", "value": [(2,3), (1,3,4,5,6)]},
"blind":       {"type": "shortform_words", "value": [(1,2), (1,2,3)]}, 
"braille":     {"type": "shortform_words", "value": [(1,2),(1,2,3,5),(1,2,3)]}, 
"children":    {"type": "shortform_words", "value": [(1,6), (1,3,4,5)]}, 
"conceive":    {"type": "shortform_words", "value": [(2,5), (1,4), (1,2,3,6)]},
"conceiving":  {"type": "shortform_words", "value": [(2,5), (1,4), (1,2,3,6), (1,2,4,5)]},
"could":       {"type": "shortform_words", "value": [(1,4),(1,4,5)]}, 
"deceive":     {"type": "shortform_words", "value": [(1,4,5), (1,4), (1,2,3,6)]}, 
"deceiving":   {"type": "shortform_words", "value": [(1,4,5), (1,4), (1,2,3,6), (1,2,4,5)]},
"declare":     {"type": "shortform_words", "value": [(1,4,5), (1,4), (1,2,3)]}, 
"declaring":   {"type": "shortform_words", "value": [(1,4,5), (1,4), (1,2,3), (1,2,4,5)]}, 
"either":      {"type": "shortform_words", "value": [(1,5), (2,4)]},
"first":       {"type": "shortform_words", "value":  [(1,2,4),(3,4)]}, 
"friend":      {"type": "shortform_words", "value": [(1,2,4), (1,2,3,5)]},
"good":        {"type": "shortform_words", "value": [(1,2,4,5), (1,4,5)]},
"great":       {"type": "shortform_words", "value": [(1,2,4,5), (1,2,3,5),(2,3,4,5)]},
"herself":     {"type": "shortform_words", "value": [(1,2,5), (1,2,4,5,6),(1,2,4)]}, 
"him":         {"type": "shortform_words", "value": [(1,2,5), (1,3,4)]},
"himself":     {"type": "shortform_words", "value": [(1,2,5), (1,3,4),(1,2,4)]}, 
"immediate":   {"type": "shortform_words", "value": [(2,4), (1,3,4),(1,3,4)]}, 
"its":         {"type": "shortform_words", "value": [(1,3,4,6),(2,3,4)]},  
"itself":      {"type": "shortform_words", "value": [(1,3,4,6), (1,2,4)]},  
"letter":      {"type": "shortform_words", "value": [(1,2,3), (1,2,3,5)]}, 
"little":      {"type": "shortform_words", "value": [(1,2,3), (1,2,3)]}, 
"much":        {"type": "shortform_words", "value": [(1,3,4), (1,6)]},
"must":        {"type": "shortform_words", "value": [(1,3,4), (3,4)]}, 
"myself":      {"type": "shortform_words", "value": [(1,3,4), (1,3,4,5,6),(1,2,4)]},
"necessary":   {"type": "shortform_words", "value": [(1,3,4,5), (1,5),(1,4)]},
"neither":     {"type": "shortform_words", "value": [(1,3,4,5), (1,5),(2,4)]}, 
"oneself":     {"type": "shortform_words", "value": [(5,),(1,3,5), (1,2,4)]}, 
"ourselves":   {"type": "shortform_words", "value": [(1,2,5,6), (1,2,3,5),(1,2,3,6),(2,3,4)]},
"paid":        {"type": "shortform_words", "value": [(1,2,3,4), (1,4,5)]}, 
"perceive":    {"type": "shortform_words", "value": [(1,2,3,4), (1,2,4,5,6),(1,4),(1,2,3,6)]},
"perceiving":  {"type": "shortform_words", "value": [(1,2,3,4), (1,2,4,5,6), (1,4), (1,2,3,6),(1,2,4,6)]}, 
"perhaps":     {"type": "shortform_words", "value": [(1,2,3,4), (1,2,4,5,6),(1,2,5)]}, 
"quick":       {"type": "shortform_words", "value": [(1,2,3,4,5), (1,3)]}, 
"receive":     {"type": "shortform_words", "value": [(1,2,3,5), (1,4),(1,2,3,6)]}, 
"receiving":   {"type": "shortform_words", "value": [(1,2,3,5), (1,4), (1,2,3,6), (1,2,4,5)]},
"rejoice":     {"type": "shortform_words", "value": [(1,2,3,5), (2,4,5), (1,4)]},
"rejoicing":   {"type": "shortform_words", "value": [(1,2,3,5), (2,4,5), (1,4), (1,2,4,5)]},
"said":        {"type": "shortform_words", "value": [(2,3,4), (1,4,5)]},
"should":      {"type": "shortform_words", "value": [(1,4,6), (1,4,5)]},
"such":        {"type": "shortform_words", "value": [(2,3,4), (1,6)]}, 
"themselves":  {"type": "shortform_words", "value": [(2,3,4,6), (1,3,4),(1,2,3,6),(2,3,4)]}, 
"thyself":     {"type": "shortform_words", "value": [(1,4,5,6), (1,3,4,5,6), (1,2,4)]},
"today":       {"type": "shortform_words", "value": [(2,3,4,5), (1,4,5)]}, 
"together":    {"type": "shortform_words", "value": [(2,3,4,5), (1,2,4,5),(1,2,3,5)]}, 
"tomorrow":    {"type": "shortform_words", "value": [(2,3,4,5), (1,3,4)]}, 
"tonight":     {"type": "shortform_words", "value": [(2,3,4,5), (1,3,4,5)]}, 
"would":       {"type": "shortform_words", "value": [(2,4,5,6), (1,4,5)]}, 
"your":        {"type": "shortform_words", "value": [(1,3,4,5,6), (1,2,3,5)]}, 
"yourself":    {"type": "shortform_words", "value": [(1,3,4,5,6), (1,2,3,5),(1,2,4)]}, 
"yourselves":  {"type": "shortform_words", "value": [(1,3,4,5,6), (1,2,3,5),(1,2,3,6),(2,3,4)]}, 
"ound": {"type": "final_letter_groupsigns", "value": [(4,6),(1,4,5)]},
"ance": {"type": "final_letter_groupsigns", "value": [(4,6),(1,5)]},
"sion": {"type": "final_letter_groupsigns", "value": [(4,6),(1,3,4,5)]},
"less": {"type": "final_letter_groupsigns", "value": [(4,6),(2,3,4)]},
"ount": {"type": "final_letter_groupsigns", "value": [(4,6),(2,3,4,5)]},
"ence": {"type": "final_letter_groupsigns", "value": [(5,6),(1,5)]},
"ong":  {"type": "final_letter_groupsigns", "value": [(5,6),(1,2,4,5)]},
"ful":  {"type": "final_letter_groupsigns", "value": [(5,6),(1,2,3)]},
"tion": {"type": "final_letter_groupsigns", "value": [(5,6), (1,3,4,5)]},
"ness": {"type": "final_letter_groupsigns", "value": [(5,6),(2,3,4)]},
"ment": {"type": "final_letter_groupsigns", "value": [(5,6),(2,3,4,5)]},
"ity":  {"type": "final_letter_groupsigns", "value": [(5,6),(1,3,4,5,6)]},
"ing":  {"type": "strong_groupsigns", "value": [(3,4,6)]},
"but":        { "type": "alpha_wordsigns", "value": [(1,2)] },
"can":        { "type": "alpha_wordsigns", "value": [(1,4)] },
"do":         { "type": "alpha_wordsigns", "value": [(1,4,5)] },
"every":      { "type": "alpha_wordsigns", "value": [(1,5)] },
"from":       { "type": "alpha_wordsigns", "value": [(1,2,4)] },
"go":         { "type": "alpha_wordsigns", "value": [(1,2,4,5)] },
"have":       { "type": "alpha_wordsigns", "value": [(1,2,5)] },
"just":       { "type": "alpha_wordsigns", "value": [(2,4,5)] },
"knowledge":  { "type": "alpha_wordsigns", "value": [(1,3)] },
"like":       { "type": "alpha_wordsigns", "value": [(1,2,3)] },
"more":       { "type": "alpha_wordsigns", "value": [(1,3,4)] },
"not":        { "type": "alpha_wordsigns", "value": [(1,3,4,5)] },
"people":     { "type": "alpha_wordsigns", "value": [(1,2,3,4)] },
"quite":      { "type": "alpha_wordsigns", "value": [(1,2,3,4,5)] },
"rather":     { "type": "alpha_wordsigns", "value": [(1,2,3,5)] },
"so":         { "type": "alpha_wordsigns", "value": [(2,3,4)] },
"that":       { "type": "alpha_wordsigns", "value": [(2,3,4,5)] },
"us":         { "type": "alpha_wordsigns", "value": [(1,3,6)] },
"very":       { "type": "alpha_wordsigns", "value": [(1,2,3,6)] },
"will":       { "type": "alpha_wordsigns", "value": [(2,4,5,6)] },
"it":         { "type": "alpha_wordsigns", "value": [(1,3,4,6)] },
"you":        { "type": "alpha_wordsigns", "value": [(1,3,4,5,6)]},
"as":         { "type": "alpha_wordsigns", "value": [(1,3,5,6)]}}

with open("brailledict.json", "w") as f:
    json.dump(braille,f,indent = 4)

